CREATE TABLE [dbo].[Message]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [Nom] NVARCHAR(50) NOT NULL, 
    [Email] NVARCHAR(323) NOT NULL, 
    [Phone] NVARCHAR(12) NOT NULL, 
    [Information] NVARCHAR(MAX) NOT NULL, 
    [DateEnvoie] DATETIME NOT NULL
)
